// 要件定義書 第9章「データ要件」に基づくプロジェクトモデル定義。
// 最重要設計原則: 配置物の正本は常にmm単位。px値は保存しない。

export const SCHEMA_VERSION = "1.10.0";

/** 実寸座標系(mm)上の点 */
export interface PointMm {
  xMm: number;
  yMm: number;
}

/** 背景画像の元データpx座標。校正基準点の保存に使用する */
export interface PointPx {
  xPx: number;
  yPx: number;
}

export type ObjectType =
  | "chair"
  | "musicStand"
  | "podium"
  | "riser"
  | "instrument"
  | "shape"
  | "text";

export type ShapeKind = "rect" | "circle";
export type AnnotationKind = "text" | "line" | "arrow" | "rect" | "circle" | "dimension";

export interface ObjectStyle {
  color: string;
  fillColor: string;
  fillOpacity: number;
  labelColor: string;
  labelVisible: boolean;
  labelFontSizeMm: number;
  strokeWidthMm: number;
}

export type ObjectStylePatch = Partial<ObjectStyle>;
export type BackgroundSourceType = "image" | "pdf";

export interface CropPx {
  xPx: number;
  yPx: number;
  widthPx: number;
  heightPx: number;
}

/** 背景図面(5.1 Background) */
export interface Background {
  /** 画像のData URL(Base64埋め込み。6.3 単一ファイル化) */
  imageDataUrl: string | null;
  naturalWidthPx: number;
  naturalHeightPx: number;
  /** 読み込んだ元データの種類。PDFは選択ページをPNGへ描画して保存する */
  sourceType: BackgroundSourceType;
  /** PDFを選択したページ番号。画像の場合はnull */
  sourcePage: number | null;
  /** 90度単位の回転(FR-012) */
  rotationDeg: 0 | 90 | 180 | 270;
  /** 元画像px上の切り抜き範囲。元画像は破壊しない。nullは全体 */
  crop: CropPx | null;
  opacity: number;
  visible: boolean;
  /** 背景は初期状態でロック(10.3) */
  locked: boolean;
}

/** 縮尺校正(5.1 Calibration) */
export interface Calibration {
  /** 校正結果。未校正時はnull。等方スケール前提(6.1) */
  mmPerPixel: number | null;
  /** 校正基準点(元画像px座標で保持。再校正時に再利用) */
  pointA: PointPx | null;
  pointB: PointPx | null;
  /** 入力された実距離(mm正規化済み。FR-022) */
  realDistanceMm: number | null;
  calibratedAt: string | null;
}

/** Phase 4の吸着設定。値は実寸mmで保持し、ズームには依存しない。 */
export interface SnapSettings {
  grid: boolean;
  objects: boolean;
  stageCenter: boolean;
  gridIntervalMm: number;
  thresholdMm: number;
  guides?: boolean;
  guideThresholdMm?: number;
}

export interface StageTemplate {
  kind: "rectangular-grid";
  widthMm: number;
  depthMm: number;
  gridIntervalMm: number;
  horizontalAnchor: "center";
  verticalAnchor: "bottom";
}

export type GuideKind = "horizontal" | "vertical" | "stageCenter" | "stageFrontOffset" | "radial" | "arc";

export interface Guide {
  id: string;
  kind: GuideKind;
  xMm: number;
  yMm: number;
  angleDeg: number;
  radiusMm: number;
  startAngleDeg: number;
  endAngleDeg: number;
  distanceMm: number | null;
  podiumId: string | null;
  locked: boolean;
  visible: boolean;
  autoGenerated?: boolean;
}

/** 画面表示状態。実寸データへ影響させない(9.4) */
export interface ViewState {
  /** 表示倍率: 画面px / mm */
  zoom: number;
  panX: number;
  panY: number;
}

export interface Layer {
  id: string;
  name: string;
  visible: boolean;
  locked: boolean;
}

/** 配置オブジェクト(9.2 SceneObject最低項目) */
export interface SceneObject {
  id: string;
  type: ObjectType;
  presetId: string | null;
  /** 原本・生成図形のvariantを識別する表示資産ID。物理寸法の正本ではない。 */
  assetVariantId?: string;
  name: string;
  /** 基準点(中心)の実寸座標 */
  xMm: number;
  yMm: number;
  /** 実寸寸法。正数のみ。回転してもwidth/depthは入れ替えない(6.2) */
  widthMm: number;
  depthMm: number;
  /** 2Dでは非表示だがPhase 0から必須(FR-046)。山台は段高 */
  heightMm: number;
  /** 0〜360へ正規化 */
  rotationDeg: number;
  label: string;
  /** 載っている山台のID(FR-063、Phase 4) */
  onRiserId: string | null;
  /** "seated" | "standing" | null (Phase 5) */
  avatar: string | null;
  locked: boolean;
  /** 表示・出力には残すが、通常の選択・編集・複製対象から外す背景化状態。 */
  backgroundFixed?: boolean;
  visible: boolean;
  groupId: string | null;
  layerId: string;
  zIndex: number;
  shape: ShapeKind;
  /** 参考図のような色・塗り・ラベル表示を保存する表示属性。 */
  style?: ObjectStylePatch;
  /** Phase 4注釈。通常の配置物ではnullまたは未指定。 */
  annotationKind?: AnnotationKind | null;
  /** 線・矢印・寸法線の終点。pxではなくmmで保持する。 */
  endXMm?: number | null;
  endYMm?: number | null;
}

/** 壁トレース(9.3)。Phase 5で使用、Phase 0で型定義のみ */
export interface Wall {
  id: string;
  points: PointMm[];
  /** 押し出し高さ。既定6000mm */
  heightMm: number;
  closed: boolean;
}

export interface ProjectMetadata {
  hallName: string;
  performanceName: string;
  date: string;
  author: string;
  notes: string;
}

export interface ExportSettings {
  paper: "A4" | "A3";
  orientation: "portrait" | "landscape";
  /** 印刷縮尺(FR-082) */
  scale: "1:50" | "1:100" | "fit";
}
export type InstrumentLabelLanguage = "ja" | "enShort";

/** Project-wide instrument label display settings. */
export interface ProjectDisplaySettings {
  instrumentLabelsVisible: boolean;
  instrumentLabelLanguage: InstrumentLabelLanguage;
}

/** プロジェクト(9.1) */
export interface Project {
  schemaVersion: string;
  id: string;
  name: string;
  metadata: ProjectMetadata;
  background: Background;
  calibration: Calibration;
  view: ViewState;
  layers: Layer[];
  objects: SceneObject[];
  guides: Guide[];
  /** Phase 0から予約。MVPでは空配列 */
  walls: Wall[];
  /** 舞台前端。Phase 5の客席視点に使用 */
  stageFront: { yMm: number } | null;
  /** Background画像なしで作成する実寸の舞台テンプレート */
  stageTemplate: StageTemplate | null;
  exportSettings: ExportSettings;
  displaySettings: ProjectDisplaySettings;
  snapSettings: SnapSettings;
  updatedAt: string;
}

