// 編集専用ガイドの純粋な幾何計算。
// 座標はすべてmm。SVGのpxやReducer、Projectの保存処理には依存しない。

import type { Guide, GuideKind, PointMm } from "../types/project";

export interface GuideBounds {
  minXMm: number;
  minYMm: number;
  maxXMm: number;
  maxYMm: number;
}

export interface GuideLineGeometry {
  kind: "line";
  start: PointMm;
  end: PointMm;
}

export interface GuideArcGeometry {
  kind: "arc";
  center: PointMm;
  radiusMm: number;
  startAngleDeg: number;
  endAngleDeg: number;
}

export type GuideGeometry = GuideLineGeometry | GuideArcGeometry;

export interface GuideSnapCandidate {
  guideId: string;
  point: PointMm;
  distanceMm: number;
}

export interface GuideAnchor {
  id: string;
  xMm: number;
  yMm: number;
}

const EPSILON = 1e-9;

function finite(value: number, fallback: number): number {
  return Number.isFinite(value) ? value : fallback;
}

export function normalizeGuideAngle(value: number): number {
  return ((finite(value, 0) % 360) + 360) % 360;
}

export function resolveGuideAnchor(guide: Guide, anchors: readonly GuideAnchor[] = []): Guide {
  const normalized = normalizeGuide(guide);
  if (!normalized.podiumId) return normalized;
  const anchor = anchors.find((candidate) => candidate.id === normalized.podiumId);
  return anchor
    ? normalizeGuide({ ...normalized, xMm: anchor.xMm, yMm: anchor.yMm })
    : normalized;
}

export function positiveAngleDelta(startAngleDeg: number, endAngleDeg: number): number {
  const delta = (finite(endAngleDeg, 0) - finite(startAngleDeg, 0)) % 360;
  return (delta + 360) % 360;
}

export function normalizeGuide(guide: Guide): Guide {
  const kind = guide.kind;
  const radiusMm = kind === "arc" ? Math.max(1, finite(guide.radiusMm, 1)) : Math.max(0, finite(guide.radiusMm, 0));
  const distanceMm = kind === "stageFrontOffset"
    ? Math.max(0, finite(guide.distanceMm ?? 0, 0))
    : null;
  return {
    ...guide,
    xMm: finite(guide.xMm, 0),
    yMm: finite(guide.yMm, 0),
    angleDeg: normalizeGuideAngle(guide.angleDeg),
    radiusMm,
    startAngleDeg: normalizeGuideAngle(guide.startAngleDeg),
    endAngleDeg: normalizeGuideAngle(guide.endAngleDeg),
    distanceMm,
    podiumId: typeof guide.podiumId === "string" ? guide.podiumId : null,
    locked: Boolean(guide.locked),
    visible: guide.visible !== false,
  };
}

function baseGuide(id: string, kind: GuideKind, xMm = 0, yMm = 0): Guide {
  return {
    id,
    kind,
    xMm,
    yMm,
    angleDeg: 0,
    radiusMm: 0,
    startAngleDeg: 0,
    endAngleDeg: 90,
    distanceMm: null,
    podiumId: null,
    locked: false,
    visible: true,
  };
}

export function createHorizontalGuide(id: string, yMm = 0): Guide {
  return baseGuide(id, "horizontal", 0, yMm);
}

export function createVerticalGuide(id: string, xMm = 0): Guide {
  return baseGuide(id, "vertical", xMm, 0);
}

export function createStageCenterGuide(id: string, stageWidthMm: number): Guide {
  return { ...baseGuide(id, "stageCenter", Math.max(0, stageWidthMm) / 2), autoGenerated: true };
}

export function createStageFrontGuide(id: string, stageFrontYMm: number, distanceMm = 0): Guide {
  const distance = Math.max(0, finite(distanceMm, 0));
  return {
    ...baseGuide(id, "stageFrontOffset", 0, stageFrontYMm - distance),
    distanceMm: distance,
    autoGenerated: true,
  };
}

export function createRadialGuide(id: string, origin: PointMm, angleDeg = 0, podiumId: string | null = null): Guide {
  return {
    ...baseGuide(id, "radial", origin.xMm, origin.yMm),
    angleDeg: normalizeGuideAngle(angleDeg),
    podiumId,
  };
}

export function createArcGuide(
  id: string,
  center: PointMm,
  radiusMm: number,
  startAngleDeg = 0,
  endAngleDeg = 90,
): Guide {
  return {
    ...baseGuide(id, "arc", center.xMm, center.yMm),
    radiusMm: Math.max(1, finite(radiusMm, 1)),
    startAngleDeg: normalizeGuideAngle(startAngleDeg),
    endAngleDeg: normalizeGuideAngle(endAngleDeg),
  };
}

export function synchronizeGeneratedGuides(
  guides: readonly Guide[],
  context: { stageWidthMm?: number | null; stageFrontYMm?: number | null },
): Guide[] {
  return guides.map((guide) => {
    if (!guide.autoGenerated) return normalizeGuide(guide);
    if (guide.kind === "stageCenter" && typeof context.stageWidthMm === "number" && context.stageWidthMm > 0) {
      return normalizeGuide({ ...guide, xMm: context.stageWidthMm / 2 });
    }
    if (
      guide.kind === "stageFrontOffset"
      && typeof context.stageFrontYMm === "number"
      && Number.isFinite(context.stageFrontYMm)
    ) {
      const distanceMm = Math.max(0, guide.distanceMm ?? 0);
      return normalizeGuide({ ...guide, distanceMm, yMm: context.stageFrontYMm - distanceMm });
    }
    return normalizeGuide(guide);
  });
}

export function movedGuideCoordinates(guide: Guide, delta: PointMm): PointMm {
  const normalized = normalizeGuide(guide);
  if (normalized.kind === "horizontal" || normalized.kind === "stageFrontOffset") {
    return { xMm: normalized.xMm, yMm: normalized.yMm + delta.yMm };
  }
  if (normalized.kind === "vertical" || normalized.kind === "stageCenter") {
    return { xMm: normalized.xMm + delta.xMm, yMm: normalized.yMm };
  }
  return { xMm: normalized.xMm + delta.xMm, yMm: normalized.yMm + delta.yMm };
}

function direction(angleDeg: number): PointMm {
  const radians = (angleDeg * Math.PI) / 180;
  return { xMm: Math.cos(radians), yMm: Math.sin(radians) };
}

function pointOnCircle(center: PointMm, radiusMm: number, angleDeg: number): PointMm {
  const unit = direction(angleDeg);
  return { xMm: center.xMm + unit.xMm * radiusMm, yMm: center.yMm + unit.yMm * radiusMm };
}

function angleOf(point: PointMm, center: PointMm): number {
  return normalizeGuideAngle((Math.atan2(point.yMm - center.yMm, point.xMm - center.xMm) * 180) / Math.PI);
}

export function angleIsOnArc(angleDeg: number, startAngleDeg: number, endAngleDeg: number): boolean {
  const span = positiveAngleDelta(startAngleDeg, endAngleDeg);
  if (span <= EPSILON) return Math.abs(normalizeGuideAngle(angleDeg) - normalizeGuideAngle(startAngleDeg)) <= EPSILON;
  const fromStart = positiveAngleDelta(startAngleDeg, angleDeg);
  return fromStart <= span + EPSILON;
}

function lineKind(guide: Guide): "horizontal" | "vertical" | null {
  if (guide.kind === "horizontal" || guide.kind === "stageFrontOffset") return "horizontal";
  if (guide.kind === "vertical" || guide.kind === "stageCenter") return "vertical";
  return null;
}

function rayEnd(guide: Guide, bounds: GuideBounds): PointMm {
  const origin = { xMm: guide.xMm, yMm: guide.yMm };
  const unit = direction(guide.angleDeg);
  const candidates: number[] = [];
  if (Math.abs(unit.xMm) > EPSILON) {
    for (const xMm of [bounds.minXMm, bounds.maxXMm]) {
      const t = (xMm - origin.xMm) / unit.xMm;
      if (t >= 0) {
        const yMm = origin.yMm + unit.yMm * t;
        if (yMm >= bounds.minYMm - EPSILON && yMm <= bounds.maxYMm + EPSILON) candidates.push(t);
      }
    }
  }
  if (Math.abs(unit.yMm) > EPSILON) {
    for (const yMm of [bounds.minYMm, bounds.maxYMm]) {
      const t = (yMm - origin.yMm) / unit.yMm;
      if (t >= 0) {
        const xMm = origin.xMm + unit.xMm * t;
        if (xMm >= bounds.minXMm - EPSILON && xMm <= bounds.maxXMm + EPSILON) candidates.push(t);
      }
    }
  }
  const lengthMm = Math.max(...candidates, Math.hypot(bounds.maxXMm - bounds.minXMm, bounds.maxYMm - bounds.minYMm) * 2, 1000);
  return { xMm: origin.xMm + unit.xMm * lengthMm, yMm: origin.yMm + unit.yMm * lengthMm };
}

export function guideGeometry(guide: Guide, bounds: GuideBounds): GuideGeometry {
  const normalized = normalizeGuide(guide);
  const kind = lineKind(normalized);
  if (kind === "horizontal") {
    return { kind: "line", start: { xMm: bounds.minXMm, yMm: normalized.yMm }, end: { xMm: bounds.maxXMm, yMm: normalized.yMm } };
  }
  if (kind === "vertical") {
    return { kind: "line", start: { xMm: normalized.xMm, yMm: bounds.minYMm }, end: { xMm: normalized.xMm, yMm: bounds.maxYMm } };
  }
  if (normalized.kind === "radial") {
    return { kind: "line", start: { xMm: normalized.xMm, yMm: normalized.yMm }, end: rayEnd(normalized, bounds) };
  }
  return {
    kind: "arc",
    center: { xMm: normalized.xMm, yMm: normalized.yMm },
    radiusMm: normalized.radiusMm,
    startAngleDeg: normalized.startAngleDeg,
    endAngleDeg: normalized.endAngleDeg,
  };
}

export function guideArcPath(geometry: GuideArcGeometry): string {
  const start = pointOnCircle(geometry.center, geometry.radiusMm, geometry.startAngleDeg);
  const end = pointOnCircle(geometry.center, geometry.radiusMm, geometry.endAngleDeg);
  const largeArc = positiveAngleDelta(geometry.startAngleDeg, geometry.endAngleDeg) > 180 ? 1 : 0;
  return `M ${start.xMm} ${start.yMm} A ${geometry.radiusMm} ${geometry.radiusMm} 0 ${largeArc} 1 ${end.xMm} ${end.yMm}`;
}

export function closestPointOnGuide(point: PointMm, guide: Guide): PointMm {
  const normalized = normalizeGuide(guide);
  const kind = lineKind(normalized);
  if (kind === "horizontal") return { xMm: point.xMm, yMm: normalized.yMm };
  if (kind === "vertical") return { xMm: normalized.xMm, yMm: point.yMm };
  if (normalized.kind === "radial") {
    const unit = direction(normalized.angleDeg);
    const t = Math.max(0, (point.xMm - normalized.xMm) * unit.xMm + (point.yMm - normalized.yMm) * unit.yMm);
    return { xMm: normalized.xMm + unit.xMm * t, yMm: normalized.yMm + unit.yMm * t };
  }
  const center = { xMm: normalized.xMm, yMm: normalized.yMm };
  const dx = point.xMm - center.xMm;
  const dy = point.yMm - center.yMm;
  const distance = Math.hypot(dx, dy);
  if (distance <= EPSILON) return pointOnCircle(center, normalized.radiusMm, normalized.startAngleDeg);
  const angle = angleOf(point, center);
  if (angleIsOnArc(angle, normalized.startAngleDeg, normalized.endAngleDeg)) {
    return pointOnCircle(center, normalized.radiusMm, angle);
  }
  const start = pointOnCircle(center, normalized.radiusMm, normalized.startAngleDeg);
  const end = pointOnCircle(center, normalized.radiusMm, normalized.endAngleDeg);
  return Math.hypot(point.xMm - start.xMm, point.yMm - start.yMm) <= Math.hypot(point.xMm - end.xMm, point.yMm - end.yMm) ? start : end;
}

export function nearestGuideSnap(point: PointMm, guides: readonly Guide[], thresholdMm: number, anchors: readonly GuideAnchor[] = []): GuideSnapCandidate | null {
  const threshold = Math.max(0, finite(thresholdMm, 0));
  let best: GuideSnapCandidate | null = null;
  for (const guide of guides) {
    const resolved = resolveGuideAnchor(guide, anchors);
    if (!resolved.visible) continue;
    const candidate = closestPointOnGuide(point, resolved);
    const distanceMm = Math.hypot(candidate.xMm - point.xMm, candidate.yMm - point.yMm);
    if (distanceMm <= threshold && (!best || distanceMm < best.distanceMm)) {
      best = { guideId: resolved.id, point: candidate, distanceMm };
    }
  }
  return best;
}

function cross(a: PointMm, b: PointMm): number {
  return a.xMm * b.yMm - a.yMm * b.xMm;
}

function subtract(a: PointMm, b: PointMm): PointMm {
  return { xMm: a.xMm - b.xMm, yMm: a.yMm - b.yMm };
}

function add(a: PointMm, b: PointMm): PointMm {
  return { xMm: a.xMm + b.xMm, yMm: a.yMm + b.yMm };
}

function scale(point: PointMm, factor: number): PointMm {
  return { xMm: point.xMm * factor, yMm: point.yMm * factor };
}

function uniquePoints(points: PointMm[]): PointMm[] {
  return points.filter((point, index) => points.findIndex((other) => Math.hypot(other.xMm - point.xMm, other.yMm - point.yMm) <= 1e-6) === index);
}

function pointOnArc(point: PointMm, guide: Guide): boolean {
  return angleIsOnArc(angleOf(point, { xMm: guide.xMm, yMm: guide.yMm }), guide.startAngleDeg, guide.endAngleDeg);
}

function lineLineIntersections(a: Guide, b: Guide): PointMm[] {
  const aKind = lineKind(a);
  const bKind = lineKind(b);
  if (!aKind || !bKind || aKind === bKind) return [];
  return aKind === "horizontal"
    ? [{ xMm: b.xMm, yMm: a.yMm }]
    : [{ xMm: a.xMm, yMm: b.yMm }];
}

function radialLineIntersections(radial: Guide, line: Guide): PointMm[] {
  const kind = lineKind(line);
  if (!kind) return [];
  const unit = direction(radial.angleDeg);
  const t = kind === "horizontal"
    ? Math.abs(unit.yMm) <= EPSILON ? null : (line.yMm - radial.yMm) / unit.yMm
    : Math.abs(unit.xMm) <= EPSILON ? null : (line.xMm - radial.xMm) / unit.xMm;
  if (t === null || t < -EPSILON) return [];
  return [{ xMm: radial.xMm + unit.xMm * t, yMm: radial.yMm + unit.yMm * t }];
}

function radialRadialIntersections(a: Guide, b: Guide): PointMm[] {
  const da = direction(a.angleDeg);
  const db = direction(b.angleDeg);
  const denominator = cross(da, db);
  if (Math.abs(denominator) <= EPSILON) return [];
  const between = subtract({ xMm: b.xMm, yMm: b.yMm }, { xMm: a.xMm, yMm: a.yMm });
  const ta = cross(between, db) / denominator;
  const tb = cross(between, da) / denominator;
  return ta >= -EPSILON && tb >= -EPSILON ? [add({ xMm: a.xMm, yMm: a.yMm }, scale(da, ta))] : [];
}

function lineArcIntersections(line: Guide, arc: Guide): PointMm[] {
  const kind = lineKind(line);
  if (!kind) return [];
  const center = { xMm: arc.xMm, yMm: arc.yMm };
  if (kind === "horizontal") {
    const dy = line.yMm - center.yMm;
    const remaining = arc.radiusMm * arc.radiusMm - dy * dy;
    if (remaining < -EPSILON) return [];
    const dx = Math.sqrt(Math.max(0, remaining));
    return uniquePoints([
      { xMm: center.xMm - dx, yMm: line.yMm },
      { xMm: center.xMm + dx, yMm: line.yMm },
    ].filter((point) => pointOnArc(point, arc)));
  }
  const dx = line.xMm - center.xMm;
  const remaining = arc.radiusMm * arc.radiusMm - dx * dx;
  if (remaining < -EPSILON) return [];
  const dy = Math.sqrt(Math.max(0, remaining));
  return uniquePoints([
    { xMm: line.xMm, yMm: center.yMm - dy },
    { xMm: line.xMm, yMm: center.yMm + dy },
  ].filter((point) => pointOnArc(point, arc)));
}

function radialArcIntersections(radial: Guide, arc: Guide): PointMm[] {
  const unit = direction(radial.angleDeg);
  const q = subtract({ xMm: radial.xMm, yMm: radial.yMm }, { xMm: arc.xMm, yMm: arc.yMm });
  const b = 2 * (q.xMm * unit.xMm + q.yMm * unit.yMm);
  const c = q.xMm * q.xMm + q.yMm * q.yMm - arc.radiusMm * arc.radiusMm;
  const discriminant = b * b - 4 * c;
  if (discriminant < -EPSILON) return [];
  const root = Math.sqrt(Math.max(0, discriminant));
  const roots = [(-b - root) / 2, (-b + root) / 2];
  return uniquePoints(
    roots
      .filter((t) => t >= -EPSILON)
      .map((t) => add({ xMm: radial.xMm, yMm: radial.yMm }, scale(unit, t)))
      .filter((point) => pointOnArc(point, arc)),
  );
}

function arcArcIntersections(a: Guide, b: Guide): PointMm[] {
  const first = { xMm: a.xMm, yMm: a.yMm };
  const second = { xMm: b.xMm, yMm: b.yMm };
  const delta = subtract(second, first);
  const distance = Math.hypot(delta.xMm, delta.yMm);
  if (distance <= EPSILON || distance > a.radiusMm + b.radiusMm + EPSILON || distance < Math.abs(a.radiusMm - b.radiusMm) - EPSILON) return [];
  const along = (a.radiusMm * a.radiusMm - b.radiusMm * b.radiusMm + distance * distance) / (2 * distance);
  const heightSquared = a.radiusMm * a.radiusMm - along * along;
  if (heightSquared < -EPSILON) return [];
  const height = Math.sqrt(Math.max(0, heightSquared));
  const base = add(first, scale(delta, along / distance));
  const perpendicular = { xMm: -delta.yMm / distance, yMm: delta.xMm / distance };
  return uniquePoints([
    add(base, scale(perpendicular, height)),
    add(base, scale(perpendicular, -height)),
  ].filter((point) => pointOnArc(point, a) && pointOnArc(point, b)));
}

/** ガイド同士の交点。無限線、放射線、円弧の範囲を尊重する。 */
export function intersectGuides(first: Guide, second: Guide): PointMm[] {
  const a = normalizeGuide(first);
  const b = normalizeGuide(second);
  const aLine = lineKind(a);
  const bLine = lineKind(b);
  if (aLine && bLine) return lineLineIntersections(a, b);
  if (a.kind === "radial" && bLine) return radialLineIntersections(a, b);
  if (b.kind === "radial" && aLine) return radialLineIntersections(b, a);
  if (a.kind === "radial" && b.kind === "radial") return radialRadialIntersections(a, b);
  if (aLine && b.kind === "arc") return lineArcIntersections(a, b);
  if (bLine && a.kind === "arc") return lineArcIntersections(b, a);
  if (a.kind === "radial" && b.kind === "arc") return radialArcIntersections(a, b);
  if (b.kind === "radial" && a.kind === "arc") return radialArcIntersections(b, a);
  if (a.kind === "arc" && b.kind === "arc") return arcArcIntersections(a, b);
  return [];
}
