// プロジェクトの生成・保存・復元(FR-001〜003、6.3 保存・互換性の詳細要件)。
// 自動テスト必須領域(11.4): 保存・復元・スキーマ移行。

import {
  SCHEMA_VERSION,
  type BackgroundSourceType,
  type Guide,
  type Layer,
  type Project,
  type SceneObject,
  type Wall,
} from "../types/project";
import { clampCrop, normalizeDeg } from "./transform";
import { createStageTemplate, KEN_MM } from "./stageTemplate";
import { normalizeGuide } from "./guides";
import { parseObjectStyle } from "./visualStyle";
import {
  CONCERT_TOM_SET_LAYOUT,
  INSTRUMENT_BODY_MASTERS,
  LEGACY_DRUM_SET_PRESET_ID,
  LEGACY_INSTRUMENT_BODY_MASTERS,
  LEGACY_XYLOPHONE_PRESET_ID,
  PREVIOUS_INSTRUMENT_BODY_MASTERS,
  SCHEMA_1_5_INSTRUMENT_BODY_MASTERS,
  TIMPANI_SET_LAYOUT,
} from "./instrumentCatalog";
import { defaultAssetVariantIdForPreset, resolveAssetVariantId } from "./symbolAssets";

let idCounter = 0;

/** プロジェクト内で一意のIDを生成する */
export function generateId(prefix: string): string {
  idCounter += 1;
  return `${prefix}-${Date.now().toString(36)}-${idCounter.toString(36)}`;
}

export const DEFAULT_LAYER_ID = "layer-objects";

export function createEmptyProject(name: string): Project {
  return {
    schemaVersion: SCHEMA_VERSION,
    id: generateId("project"),
    name,
    metadata: { hallName: "", performanceName: "", date: "", author: "", notes: "" },
    background: {
      imageDataUrl: null,
      naturalWidthPx: 0,
      naturalHeightPx: 0,
      sourceType: "image",
      sourcePage: null,
      rotationDeg: 0,
      crop: null,
      opacity: 1,
      visible: true,
      locked: true,
    },
    calibration: {
      mmPerPixel: null,
      pointA: null,
      pointB: null,
      realDistanceMm: null,
      calibratedAt: null,
    },
    view: { zoom: 0.04, panX: 40, panY: 40 },
    layers: [
      { id: "layer-background", name: "背景", visible: true, locked: true },
      { id: DEFAULT_LAYER_ID, name: "オブジェクト", visible: true, locked: false },
      { id: "layer-annotations", name: "注釈", visible: true, locked: false },
    ],
    objects: [],
    guides: [],
    walls: [],
    stageTemplate: null,
    stageFront: null,
    exportSettings: { paper: "A3", orientation: "landscape", scale: "1:100" },
    displaySettings: { instrumentLabelsVisible: true, instrumentLabelLanguage: "ja" },
    // 舞台中央線と編集ガイドは既定で有効。グリッド(910mm)と他オブジェクト中心は
    // 椅子の実ピッチ(600mm等)と衝突しやすいため、スナップパネルからの明示指定に任せる。
    snapSettings: { grid: false, objects: false, stageCenter: true, gridIntervalMm: 910, thresholdMm: 60, guides: true, guideThresholdMm: 60 },
    updatedAt: new Date().toISOString(),
  };
}

/** プロジェクトを単一JSON文字列へ書き出す(FR-003) */
export function serializeProject(project: Project): string {
  return JSON.stringify(
    { ...project, schemaVersion: SCHEMA_VERSION, updatedAt: new Date().toISOString() },
    null,
    2,
  );
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function num(v: unknown, fallback: number): number {
  return typeof v === "number" && Number.isFinite(v) ? v : fallback;
}

function str(v: unknown, fallback: string): string {
  return typeof v === "string" ? v : fallback;
}

function bool(v: unknown, fallback: boolean): boolean {
  return typeof v === "boolean" ? v : fallback;
}

function parseLayers(raw: unknown, fallback: Layer[]): Layer[] {
  if (!Array.isArray(raw)) return fallback;
  const layers = raw.filter(isRecord).map((layer, index) => ({
    id: str(layer.id, `layer-${index}`),
    name: str(layer.name, "レイヤー"),
    visible: bool(layer.visible, true),
    locked: bool(layer.locked, false),
  }));
  return layers.length > 0 ? layers : fallback;
}

function parseSourceType(value: unknown): BackgroundSourceType {
  return value === "pdf" ? "pdf" : "image";
}

function parseAnnotationKind(value: unknown): SceneObject["annotationKind"] {
  return value === "text" || value === "line" || value === "arrow" || value === "rect" || value === "circle" || value === "dimension"
    ? value
    : null;
}
function parseGuideKind(value: unknown): Guide["kind"] {
  return value === "horizontal" || value === "vertical" || value === "stageCenter" || value === "stageFrontOffset" || value === "radial" || value === "arc"
    ? value
    : "horizontal";
}

function parseGuides(raw: unknown): Guide[] {
  if (!Array.isArray(raw)) return [];
  return raw.filter(isRecord).map((guide, index) => normalizeGuide({
    id: str(guide.id, `guide-${index}`),
    kind: parseGuideKind(guide.kind),
    xMm: num(guide.xMm, 0),
    yMm: num(guide.yMm, 0),
    angleDeg: num(guide.angleDeg, 0),
    radiusMm: num(guide.radiusMm, 0),
    startAngleDeg: num(guide.startAngleDeg, 0),
    endAngleDeg: num(guide.endAngleDeg, 90),
    distanceMm: typeof guide.distanceMm === "number" ? num(guide.distanceMm, 0) : null,
    podiumId: typeof guide.podiumId === "string" ? guide.podiumId : null,
    locked: bool(guide.locked, false),
    visible: bool(guide.visible, true),
    ...(typeof guide.autoGenerated === "boolean" ? { autoGenerated: guide.autoGenerated } : {}),
  }));
}

function schemaVersionMinor(schemaVersion: string): number | null {
  const [major, minor] = schemaVersion.split(".").map(Number);
  return major === 1 && Number.isFinite(minor) ? minor : null;
}

const LEGACY_INSTRUMENT_PRESET_ID_MIGRATIONS: Readonly<Record<string, string>> = {
  marimba: "marimba-5oct",
  vibraphone: "vibraphone-standard",
  chimes: "tubular-bells-concert",
  harp: "grand-harp-47",
  xylophone: LEGACY_XYLOPHONE_PRESET_ID,
  "drum-set": LEGACY_DRUM_SET_PRESET_ID,
};

function shouldMigrateLegacyInstrumentPresetId(schemaVersion: string): boolean {
  const minor = schemaVersionMinor(schemaVersion);
  return minor !== null && minor <= 5;
}

function migratedInstrumentPresetId(rawObject: Record<string, unknown>, schemaVersion: string): string | null {
  if (!shouldMigrateLegacyInstrumentPresetId(schemaVersion) || rawObject.type !== "instrument") return null;
  const presetId = typeof rawObject.presetId === "string" ? rawObject.presetId : null;
  return presetId ? LEGACY_INSTRUMENT_PRESET_ID_MIGRATIONS[presetId] ?? null : null;
}

function migratedRenamedInstrumentDimensions(
  rawObject: Record<string, unknown>,
  schemaVersion: string,
  oldPresetId: string | null,
  migratedPresetId: string | null,
): { widthMm: number; depthMm: number } | null {
  if (!oldPresetId || !migratedPresetId || migratedPresetId === LEGACY_XYLOPHONE_PRESET_ID || migratedPresetId === LEGACY_DRUM_SET_PRESET_ID) return null;
  const minor = schemaVersionMinor(schemaVersion);
  if (minor === null || minor > 5) return null;
  const source = minor < 4 ? LEGACY_INSTRUMENT_BODY_MASTERS : SCHEMA_1_5_INSTRUMENT_BODY_MASTERS;
  const legacy = source[oldPresetId];
  const current = INSTRUMENT_BODY_MASTERS[migratedPresetId];
  if (!legacy || !current) return null;
  if (rawObject.widthMm !== legacy.widthMm || rawObject.depthMm !== legacy.depthMm) return null;
  return { widthMm: current.widthMm, depthMm: current.depthMm };
}

function shouldMigrateInstrumentDimensions(schemaVersion: string): boolean {
  const minor = schemaVersionMinor(schemaVersion);
  return minor !== null && minor < 5;
}

const LEGACY_CRASH_CYMBAL_PAIR_DIMENSIONS = { widthMm: 550, depthMm: 300 } as const;

function migratedCrashCymbalPairDimensions(rawObject: Record<string, unknown>): { widthMm: number; depthMm: number } | null {
  if (rawObject.type !== "instrument" || rawObject.presetId !== "crash-cymbal-pair") return null;
  const current = INSTRUMENT_BODY_MASTERS["crash-cymbal-pair"];
  if (
    !current
    || rawObject.widthMm !== LEGACY_CRASH_CYMBAL_PAIR_DIMENSIONS.widthMm
    || rawObject.depthMm !== LEGACY_CRASH_CYMBAL_PAIR_DIMENSIONS.depthMm
  ) return null;
  // 550x300mm was the previous default. Only that untouched value is repaired;
  // any other persisted dimensions remain the source of truth.
  return { widthMm: current.widthMm, depthMm: current.depthMm };
}

function migratedInstrumentDimensions(rawObject: Record<string, unknown>, schemaVersion: string): { widthMm: number; depthMm: number } | null {
  if (rawObject.type !== "instrument") return null;
  const presetId = typeof rawObject.presetId === "string" ? rawObject.presetId : null;
  if (!presetId) return null;
  const migratedCrashDimensions = migratedCrashCymbalPairDimensions(rawObject);
  if (migratedCrashDimensions) return migratedCrashDimensions;
  if (!shouldMigrateInstrumentDimensions(schemaVersion)) return null;
  // 旧セットは単体4台へ展開するため、先に旧外接寸法を保持する。
  if (presetId === "timpani-set-4" || presetId === "concert-tom-set-4") return null;
  const minor = schemaVersionMinor(schemaVersion);
  const source = minor !== null && minor < 4
    ? LEGACY_INSTRUMENT_BODY_MASTERS
    : PREVIOUS_INSTRUMENT_BODY_MASTERS;
  const legacy = source[presetId];
  const current = INSTRUMENT_BODY_MASTERS[presetId];
  if (!legacy || !current) return null;
  if (rawObject.widthMm !== legacy.widthMm || rawObject.depthMm !== legacy.depthMm) return null;
  return { widthMm: current.widthMm, depthMm: current.depthMm };
}

type LegacyGroupPresetId = "timpani-set-4" | "concert-tom-set-4";
type LegacyGroupPart = { presetId: string; centerXMm: number; centerYMm: number };

function legacyGroupLayoutForPreset(presetId: LegacyGroupPresetId): readonly LegacyGroupPart[] {
  return presetId === "timpani-set-4" ? TIMPANI_SET_LAYOUT : CONCERT_TOM_SET_LAYOUT;
}

const LEGACY_CONCERT_TOM_SET_BODY_SIZE = { widthMm: 1870, depthMm: 580 } as const;

function legacyGroupDefaultSizes(presetId: LegacyGroupPresetId, schemaVersion: string): Array<{ widthMm: number; depthMm: number }> {
  const minor = schemaVersionMinor(schemaVersion);
  if (minor === null || minor >= 5) return [];
  if (presetId === "timpani-set-4") {
    const source = minor < 4 ? LEGACY_INSTRUMENT_BODY_MASTERS : PREVIOUS_INSTRUMENT_BODY_MASTERS;
    const legacy = source[presetId];
    return legacy ? [{ widthMm: legacy.widthMm, depthMm: legacy.depthMm }] : [];
  }
  // 旧仕様の4トム外接寸法。現行1490x520とは別の移行判定用履歴値。
  if (presetId === "concert-tom-set-4") return [LEGACY_CONCERT_TOM_SET_BODY_SIZE];
  const current = INSTRUMENT_BODY_MASTERS[presetId];
  return current ? [{ widthMm: current.widthMm, depthMm: current.depthMm }] : [];
}

/**
 * 旧形式の一枚ティンパニ／トムセットを、同じ中心・回転を保った4個の子要素へ変換する。
 * 既定寸法と一致しないユーザー編集値は、推測で上書きせず旧オブジェクトを残す。
 */
function migrateLegacyGroupObject(object: SceneObject, schemaVersion: string): SceneObject[] {
  const presetId = object.presetId;
  if (
    schemaVersionMinor(schemaVersion) === null
    || schemaVersionMinor(schemaVersion)! >= 5
    || object.type !== "instrument"
    || (presetId !== "timpani-set-4" && presetId !== "concert-tom-set-4")
  ) {
    return [object];
  }
  const groupPresetId = presetId as LegacyGroupPresetId;
  const defaults = legacyGroupDefaultSizes(groupPresetId, schemaVersion);
  if (!defaults.some((size) => size.widthMm === object.widthMm && size.depthMm === object.depthMm)) return [object];

  const parts = legacyGroupLayoutForPreset(groupPresetId);
  const bounds = parts.reduce(
    (result, part) => {
      const master = INSTRUMENT_BODY_MASTERS[part.presetId];
      if (!master) return result;
      return {
        minX: Math.min(result.minX, part.centerXMm - master.widthMm / 2),
        minY: Math.min(result.minY, part.centerYMm - master.depthMm / 2),
        maxX: Math.max(result.maxX, part.centerXMm + master.widthMm / 2),
        maxY: Math.max(result.maxY, part.centerYMm + master.depthMm / 2),
      };
    },
    { minX: Number.POSITIVE_INFINITY, minY: Number.POSITIVE_INFINITY, maxX: Number.NEGATIVE_INFINITY, maxY: Number.NEGATIVE_INFINITY },
  );
  const groupCenterXMm = (bounds.minX + bounds.maxX) / 2;
  const groupCenterYMm = (bounds.minY + bounds.maxY) / 2;
  const angleRad = (object.rotationDeg * Math.PI) / 180;
  const cos = Math.cos(angleRad);
  const sin = Math.sin(angleRad);
  const groupId = object.groupId ?? generateId("group");

  return parts.flatMap((part, index) => {
    const master = INSTRUMENT_BODY_MASTERS[part.presetId];
    if (!master) return [];
    const localX = part.centerXMm - groupCenterXMm;
    const localY = part.centerYMm - groupCenterYMm;
    const assetVariantId = defaultAssetVariantIdForPreset(part.presetId);
    return [{
      ...object,
      id: object.id + "-" + part.presetId,
      type: "instrument",
      presetId: part.presetId,
      ...(assetVariantId ? { assetVariantId } : {}),
      name: object.name + " / " + part.presetId,
      xMm: Math.round(object.xMm + localX * cos - localY * sin),
      yMm: Math.round(object.yMm + localX * sin + localY * cos),
      widthMm: master.widthMm,
      depthMm: master.depthMm,
      rotationDeg: object.rotationDeg,
      label: "",
      groupId,
      zIndex: object.zIndex + index,
      shape: "circle",
      annotationKind: null,
      endXMm: null,
      endYMm: null,
    } satisfies SceneObject];
  });
}

/**
 * JSONからプロジェクトを復元する。
 * 1.0.0では背景のsourceType/sourcePageが存在しなかったため既定値を補う。
 * 1.9.0で追加したオブジェクトの背景化状態は、旧JSONではfalseとして復元する。
 * 未知のフィールドは無視し、既知フィールドを復元する(6.3)。
 */
export function deserializeProject(json: string): Project {
  let raw: unknown;
  try {
    raw = JSON.parse(json);
  } catch {
    throw new Error("プロジェクトファイルのJSONを解析できません");
  }
  if (!isRecord(raw)) {
    throw new Error("プロジェクトファイルの形式が不正です");
  }
  if (typeof raw.schemaVersion !== "string") {
    throw new Error("schemaVersionがありません。プロジェクトファイルではない可能性があります");
  }
  const sourceSchemaVersion = raw.schemaVersion;
  // 1.0.0?1.3.0????????????????????????????????????
  // 将来の破壊的変更もここで版ごとに吸収し、既存JSONを読めなくしない。

  const base = createEmptyProject(str(raw.name, "無題のプロジェクト"));

  const objects: SceneObject[] = (Array.isArray(raw.objects)
    ? raw.objects.filter(isRecord).map((o, i): SceneObject => {
        const oldPresetId = typeof o.presetId === "string" ? o.presetId : null;
        const migratedPresetId = migratedInstrumentPresetId(o, sourceSchemaVersion);
        const presetId = migratedPresetId ?? oldPresetId;
        const migratedDimensions = migratedInstrumentDimensions(o, sourceSchemaVersion)
          ?? migratedRenamedInstrumentDimensions(o, sourceSchemaVersion, oldPresetId, migratedPresetId);
        const assetVariantId = resolveAssetVariantId(o.assetVariantId, presetId);
        return ({
          id: str(o.id, generateId("obj")),
          type: str(o.type, "shape") as SceneObject["type"],
          presetId,
          ...(assetVariantId ? { assetVariantId } : {}),
          name: str(o.name, "オブジェクト"),
          xMm: num(o.xMm, 0),
          yMm: num(o.yMm, 0),
          widthMm: migratedDimensions?.widthMm ?? Math.max(1, num(o.widthMm, 1)),
          depthMm: migratedDimensions?.depthMm ?? Math.max(1, num(o.depthMm, 1)),
          heightMm: Math.max(0, num(o.heightMm, 0)),
          rotationDeg: normalizeDeg(num(o.rotationDeg, 0)),
          label: str(o.label, ""),
          onRiserId: typeof o.onRiserId === "string" ? o.onRiserId : null,
          avatar: typeof o.avatar === "string" ? o.avatar : null,
          locked: bool(o.locked, false),
          backgroundFixed: bool(o.backgroundFixed, false),
          visible: bool(o.visible, true),
          groupId: typeof o.groupId === "string" ? o.groupId : null,
          layerId: str(o.layerId, DEFAULT_LAYER_ID),
          zIndex: num(o.zIndex, i),
          shape: o.shape === "circle" ? "circle" : "rect",
          style: parseObjectStyle(o.style),
          annotationKind: parseAnnotationKind(o.annotationKind),
          endXMm: typeof o.endXMm === "number" && Number.isFinite(o.endXMm) ? o.endXMm : null,
          endYMm: typeof o.endYMm === "number" && Number.isFinite(o.endYMm) ? o.endYMm : null,
        });
      })
    : []).flatMap((object) => migrateLegacyGroupObject(object, sourceSchemaVersion));

  const walls: Wall[] = Array.isArray(raw.walls)
    ? raw.walls.filter(isRecord).map((w): Wall => ({
        id: str(w.id, generateId("wall")),
        points: Array.isArray(w.points)
          ? w.points.filter(isRecord).map((p) => ({
              xMm: num(p.xMm, 0),
              yMm: num(p.yMm, 0),
            }))
          : [],
        heightMm: Math.max(0, num(w.heightMm, 6000)),
        closed: bool(w.closed, false),
      }))
    : [];

  const guides = parseGuides(raw.guides);
  const bg = isRecord(raw.background) ? raw.background : {};
  const calib = isRecord(raw.calibration) ? raw.calibration : {};
  const view = isRecord(raw.view) ? raw.view : {};
  const meta = isRecord(raw.metadata) ? raw.metadata : {};
  const exp = isRecord(raw.exportSettings) ? raw.exportSettings : {};
  const display = isRecord(raw.displaySettings) ? raw.displaySettings : {};
  const snap = isRecord(raw.snapSettings) ? raw.snapSettings : {};
  const snapSettings: Project["snapSettings"] = {
    grid: bool(snap.grid, base.snapSettings.grid),
    objects: bool(snap.objects, base.snapSettings.objects),
    stageCenter: bool(snap.stageCenter, base.snapSettings.stageCenter),
    gridIntervalMm: Math.max(1, num(snap.gridIntervalMm, base.snapSettings.gridIntervalMm)),
    thresholdMm: Math.max(0, num(snap.thresholdMm, base.snapSettings.thresholdMm)),
  };
  // guides系はPhase 4より後に追加した項目。旧JSONでも他項目と同じく既定値へ寄せる。
  snapSettings.guides = bool(snap.guides, base.snapSettings.guides ?? false);
  snapSettings.guideThresholdMm = Math.max(0, num(snap.guideThresholdMm, base.snapSettings.guideThresholdMm ?? snapSettings.thresholdMm));
  const naturalWidthPx = Math.max(0, num(bg.naturalWidthPx, 0));
  const naturalHeightPx = Math.max(0, num(bg.naturalHeightPx, 0));
  const rotationValue = bg.rotationDeg;
  const rotationDeg = ([0, 90, 180, 270] as const).includes(
    rotationValue as 0 | 90 | 180 | 270,
  )
    ? (rotationValue as 0 | 90 | 180 | 270)
    : 0;
  const crop = isRecord(bg.crop) && naturalWidthPx > 0 && naturalHeightPx > 0
    ? clampCrop(
        {
          xPx: num(bg.crop.xPx, 0),
          yPx: num(bg.crop.yPx, 0),
          widthPx: num(bg.crop.widthPx, naturalWidthPx),
          heightPx: num(bg.crop.heightPx, naturalHeightPx),
        },
        naturalWidthPx,
        naturalHeightPx,
      )
    : null;
  const stageFront = isRecord(raw.stageFront)
    ? { yMm: num(raw.stageFront.yMm, 0) }
    : null;
  const stageTemplate = isRecord(raw.stageTemplate) && raw.stageTemplate.kind === "rectangular-grid"
    ? createStageTemplate(
        num(raw.stageTemplate.widthMm, 0),
        num(raw.stageTemplate.depthMm, 0),
        num(raw.stageTemplate.gridIntervalMm, KEN_MM),
      )
    : null;


  return {
    ...base,
    schemaVersion: SCHEMA_VERSION,
    id: str(raw.id, base.id),
    name: str(raw.name, base.name),
    metadata: {
      hallName: str(meta.hallName, ""),
      performanceName: str(meta.performanceName, ""),
      date: str(meta.date, ""),
      author: str(meta.author, ""),
      notes: str(meta.notes, ""),
    },
    background: {
      imageDataUrl: typeof bg.imageDataUrl === "string" ? bg.imageDataUrl : null,
      naturalWidthPx,
      naturalHeightPx,
      sourceType: parseSourceType(bg.sourceType),
      sourcePage:
        typeof bg.sourcePage === "number" && Number.isInteger(bg.sourcePage) && bg.sourcePage > 0
          ? bg.sourcePage
          : null,
      rotationDeg,
      crop,
      opacity: Math.min(1, Math.max(0, num(bg.opacity, 1))),
      visible: bool(bg.visible, true),
      locked: bool(bg.locked, true),
    },
    calibration: {
      mmPerPixel:
        typeof calib.mmPerPixel === "number" && calib.mmPerPixel > 0
          ? calib.mmPerPixel
          : null,
      pointA: isRecord(calib.pointA)
        ? { xPx: num(calib.pointA.xPx, 0), yPx: num(calib.pointA.yPx, 0) }
        : null,
      pointB: isRecord(calib.pointB)
        ? { xPx: num(calib.pointB.xPx, 0), yPx: num(calib.pointB.yPx, 0) }
        : null,
      realDistanceMm:
        typeof calib.realDistanceMm === "number" && calib.realDistanceMm > 0
          ? calib.realDistanceMm
          : null,
      calibratedAt: typeof calib.calibratedAt === "string" ? calib.calibratedAt : null,
    },
    view: {
      zoom: Math.max(0.0001, num(view.zoom, base.view.zoom)),
      panX: num(view.panX, base.view.panX),
      panY: num(view.panY, base.view.panY),
    },
    layers: parseLayers(raw.layers, base.layers),
    objects,
    guides,
    walls,
    stageFront,
    stageTemplate,
    exportSettings: {
      paper: exp.paper === "A4" ? "A4" : "A3",
      orientation: exp.orientation === "portrait" ? "portrait" : "landscape",
      scale: exp.scale === "1:50" || exp.scale === "fit" ? exp.scale : "1:100",
    },
    displaySettings: {
      instrumentLabelsVisible: bool(display.instrumentLabelsVisible, true),
      instrumentLabelLanguage: display.instrumentLabelLanguage === "enShort" ? "enShort" : "ja",
    },
    snapSettings,
    updatedAt: str(raw.updatedAt, base.updatedAt),
  };
}

